#!/usr/bin/env bash
current_dir=$(pwd)
cm_date="20161001"
cm_version="13.0-"$cm_date"-NIGHTLY-w55n"
sha1sum="26D7771AE2743486BE62D617B751C85CB3BE661F"
zip_name_date="cm-13.0-"$cm_date"-NIGHTLY-w5.zip"

wget https://download.cyanogenmod.org/get/jenkins/181564/cm-13.0-20161001-NIGHTLY-w5.zip -O $zip_name_date
wget_gapps=$(wget https://github.com/opengapps/arm/releases/download/"$cm_date"/open_gapps-arm-6.0-pico-"$cm_date".zip -O "gapps.zip");
gapps_status=$?;

sha1sum $zip_name_date
sha1down=$sha1sum"  "$zip_name_date
sha1down_org=$(sha1sum $zip_name_date)

if [ "${sha1down_org,,}" != "${sha1down,,}" ]
then
	echo "Checksum filed";
	rm $zip_name_date
	./cm13
	exit
else 
	mkdir out
	unzip $zip_name_date -d $current_dir/out
	rm $zip_name_date

	echo "Create dirs"
	mkdir -p out/system/app/Updater
	mkdir -p out/system/usr/keylayout

	echo "Move files"
	cp /var/www/html/updates/update.apk $current_dir/out/system/app/Updater/Updater.apk
	mv $current_dir/Generic.kl $current_dir/out/system/usr/keylayout/Generic.kl
	mv $current_dir/fixup.sh $current_dir/out/fixup.sh

	echo "Edit Build.prop"
	sed -i 's/w5/w55n/g' $current_dir/out/system/build.prop
	echo '' >> $current_dir/out/system/build.prop
	echo 'ro.nfc.port=I2C' >> $current_dir/out/system/build.prop
	echo 'ro.build.description=w55n_global_com-user 4.4.2 KOT49I.A1398228431 1398228431 release-keys' >> $current_dir/out/system/build.prop
	echo 'ro.build.fingerprint=lge/w55n_global_com/w55n:4.4.2/KOT49I.A1398228431/1398228431:user/release-keys' >> $current_dir/out/system/build.prop
	echo 'persist.radio.multisim.config=none' >> $current_dir/out/system/build.prop
	echo 'telephony.lteOnCdmaDevice=0' >> $current_dir/out/system/build.prop
	echo 'ro.build.product=w55n' >> $current_dir/out/system/build.prop
	echo 'ro.product.model=LG-D280n' >> $current_dir/out/system/build.prop
	echo 'ro.product.device=w55n' >> $current_dir/out/system/build.prop
	echo 'ro.sf.hwrotation=180' >> $current_dir/out/system/build.prop

	echo "Edit updater-script"
	sed '1d' $current_dir/out/META-INF/com/google/android/updater-script > $current_dir/ups_tmp
	rm $current_dir/out/META-INF/com/google/android/updater-script
	mv $current_dir/ups_tmp $current_dir/out/META-INF/com/google/android/updater-script
	echo 'mount("ext4", "EMMC", "/dev/block/platform/msm_sdcc.1/by-name/system", "/system");' >> $current_dir/out/META-INF/com/google/android/updater-script
	echo 'package_extract_dir("system", "/system");' >> $current_dir/out/META-INF/com/google/android/updater-script
	echo 'unmount("/system");' >> $current_dir/out/META-INF/com/google/android/updater-script

	echo "Compile to zip"
	cd $current_dir/out
	zip -r $zip_name_date .
	cd $current_dir/
	mv $current_dir/out/$zip_name_date $current_dir/
	
	echo "Remove tmp files"
	rm -r $current_dir/out

	echo "Create link && send update"
	cp $current_dir/$zip_name_date /var/www/html/updates/zip/update.zip
	echo "http://app-updater.pl/updates/zip/update.zip" > /var/www/html/updates/txt/download_link.txt
	echo $cm_version > /var/www/html/updates/txt/version.txt
	echo $cm_version > /var/www/html/updates/txt/version_debug.txt
	
	echo $gapps_status

	if [ "$gapps_status" == "0" ]
	then
		echo "http://app-updater.pl/updates/zip/gapps.zip" > /var/www/html/updates/txt/download_gapps.txt
		mv $current_dir/"gapps.zip" /var/www/html/updates/zip/gapps.zip
	else
		rm $current_dir/"gapps.zip"
	fi

	echo "Create MD5"
	md5sum $zip_name_date > $zip_name_date.md5
	cd /var/www/html/updates/zip
	md5sum update.zip > $current_dir/update.zip.md5
	mv $current_dir/update.zip.md5 /var/www/html/updates/zip/update.zip.md5

	echo "Succes"
fi
